#configuracion del datasource
spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/sante
  username: sante
  password: sante
  driverClassName: org.postgresql.Driver
#configuracion para que escriba las consultas en consola
spring.jpa:
 show-sql: true
#configurar el nivel de loggeo pasa el security de spring
logging:
 level:
  org.springframework.security: DEBUG
